### ISSUE TITLE
Task list before release 1.0

### ISSUE THREAD

**Issue by ignacio-penas** [nuvla/cli#1]
- [x] Add (Or change) the order from \<action> \<entity> to \<entity> \<action> commands
- [x] Finished code documentation
- [x] Finish CLI help documentation
- [x] Simplify the starting process of real NuvlaEdge engines. Remove the start for real fleets until the isolation in on production
- [x] Add build of help and code documentation
