### ISSUE TITLE
Known Issues - TODO's

### ISSUE THREAD

**Issue by ignacio-penas** [nuvla/cli#5]
- [ ] Clean login and logout functions
- [ ] Provide the CLI with a compose project reading
- [ ] Improve decommissioning and deleting of NuvlaEdge instances by threading
- [ ] Add autobuild and push with GH actions/workflows
- [ ] Add SSH device class extending Device class. Use nuvlaedge/validation
